### ISSUE TITLE
Rails 4 Support

### ISSUE THREAD

**Issue by propven** [lingz/alphabetical_paginate#18]
Hi, I'm a relative beginner and trying to deploy your gem. 
After running bundle install I added the following to the controller

@investors, @alphaParams = Investor.alpha_paginate(params[:letter]){|investor| investor.l_name} 

And put the code in the view to display
<%= alphabetical_paginate @investors %>

I get this error when trying to load the view "undefined method `alpha_paginate' for #Class:0x007fa040152a88"

This is dev environment, sqlite. Any hints would be welcome. Thanks!

**Comment by cyx2** [comment]
Is there any update on Rails 4 compatibility?

**Comment by lingz** [comment]
I'm not doing any Rails 4 work and am unfamiliar with the framework, so would need a pull request to add Rails 4.

**Comment by substantial-philipbjorge** [comment]
I ran into the OP's issue and restarting my app server got the alpha_paginate method...
This gem appears to be Rails 4 compatible and its awesome :D.

**Comment by Petercopter** [comment]
I am getting this error on Rails 4.2:
```
NoMethodError: method `mb_chars' for nil:NilClass
/lib/alphabetical_paginate/controller_helper.rb:48:in `alpha_paginate'
```

**Comment by brentdodell** [comment]
> NoMethodError: method `mb_chars' for nil:NilClass

I was getting this as well. It was when at least one record had an empty string for the column I was paginating on. @lingz, is there a configuration that would support an empty (or nil) field?

**Comment by Petercopter** [comment]
@brentdodell @lingz There is a pull request open that fixes the problem
https://github.com/lingz/alphabetical_paginate/pull/44
But if you notice in the method params, it has `default_field: "a"`, so why isn't that being recognized? I came to the same solution as the PR author... but why does it work?! All the other params work, and it works in Rails 3.2....

For the meantime, it looks like setting the `default_field` option when instantiating seems to work.

**Comment by lingz** [comment]
Above commenters have verified it's rails 4 compatible.
